version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: /tmp/workspace
    steps:
      - checkout
      - run:
          name: install packages
          command: |
              yarn install
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:latest
    working_directory: /tmp/workspace
    parallelism: 2
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: test
          command: |
              TESTFILES=$(circleci tests glob "__tests__/**/*.test.js" | circleci tests split --split-by=timings)
              yarn test $TESTFILES
      - store_test_results:
          path: test_results
workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test:
        requires:
          - build
