version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: yarn install
          command:
            yarn install
      - run:
          name: run test
          command:
            yarn run test
workflows:
  version: 2
  build:
    jobs:
      - build
