version: 2
jobs:
  build-failed:
    docker:
      - image: circleci/python@sha256:5f1335f1ad01744fae0c38c6fcfd142dc5a9b1a611d314638290dd5589f4823f
    steps:
      - run:
          command: |
            pip --version
            virtualenv --version
            which virtualenv
  build-success:
    docker:
      - image: circleci/python@sha256:19a446501d3e0ca273ed3161eeca3780dadbc9e3f3a788c8fd2bc92f5ed9bed0
    steps:
      - run:
          command: |
            pip --version
            virtualenv --version
            which virtualenv
  current:
    docker:
      - image: circleci/python:3.6
    steps:
      - run:
          command: |
            pip --version
            virtualenv --version
            which virtualenv

workflows:
  version: 2
  workflow:
    jobs:
      - build-success
      - build-failed
      - current
