version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-jessie-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: remove default nodejs
          command: |
            node -v
            which node
            sudo rm /usr/local/bin/node
      - run:
          name: nvm install and set node version
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'  >> $BASH_ENV
            echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"' >> $BASH_ENV  # This loads nvm bash_completion
            source $BASH_ENV
            nvm install 12.1.0
            nvm alias default 12.1.0
            node -v
            which node
      - run: |
          node -v
          which node
